site_name: 'PSSysTray'
site_description: 'Documentation for PowerShell Module: PSSysTray'
site_author: 'Pierre Smit'
site_url: 'https://smitpi.github.io/PSSysTray'
 
repo_url: 'https://github.com/smitpi/PSSysTray'
repo_name:  'smitpi/PSSysTray'
 
copyright: '(c) Pierre Smit. All rights reserved.'
 
extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github-square
      link: 'https://smitpi.github.io/PSSysTray'
 
markdown_extensions:
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
 
theme: windmill
